<?php
	class Mlaporan_paket extends CI_Model {

		function __construct() {
			// Call the Model constructor
			parent:: __construct();
			$this->db = $this->load->database('report', TRUE);
			//set waktu yang digunakan ke zona jakarta
			//$this->db->query("SET time_zone='Asia/Jakarta'");
		}
      	function tanggal_indo($tanggal){
	        $bulan = array (1 =>   'Januari',
	              'Februari',
	              'Maret',
	              'April',
	              'Mei',
	              'Juni',
	              'Juli',
	              'Agustus',
	              'September',
	              'Oktober',
	              'November',
	              'Desember'
	            );
	        $split = explode('-', $tanggal);
	        return $split[2] . ' ' . $bulan[ (int)$split[1] ] . ' ' . $split[0];
    	}
    	function get_nm_paket(){
        	$sql = "SELECT * FROM M_PAKET where AKTIF = 1 AND TIPE != 'PARSIAL'";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_nama_paket($param1=''){
        	$sql = "SELECT KETERANGAN FROM M_PAKET WHERE ID_PAKET = '$param1'";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_tgl_masuk(){
        	$sql = "SELECT DISTINCT TO_CHAR (TGL_REGISTRASI, 'YYYY') AS tahunnya FROM T_FO ORDER BY tahunnya ASC";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_dasboard($tahun='',$param1=''){
        	$sql = "SELECT no_bulan, Bulan, Tahun, KETERANGAN, COUNT (Bulan) AS total FROM ( SELECT TO_CHAR ( DATA_PEMOHON.TGL_REGISTRASI, 'Month' ) AS Bulan, TO_CHAR ( DATA_PEMOHON.TGL_REGISTRASI, 'mm' ) AS no_bulan, TO_CHAR ( DATA_PEMOHON.TGL_REGISTRASI, 'yyyy' ) AS Tahun, KETERANGAN FROM DATA_PEMOHON, T_FO, M_PAKET WHERE T_FO.NO_REGISTRASI = DATA_PEMOHON.NO_REGISTRASI AND T_FO.ID_PAKET = M_PAKET.ID_PAKET AND TO_CHAR ( DATA_PEMOHON.TGL_REGISTRASI, 'ddmmyyyy' ) = TO_CHAR ( T_FO.TGL_REGISTRASI, 'ddmmyyyy' ) AND T_FO.ID_PAKET = '$param1' AND ID_ALUR_PROSES != 100 ) WHERE Tahun = '$tahun' GROUP BY no_bulan, Bulan, Tahun, KETERANGAN ORDER BY no_bulan ASC";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_dasboard_imb_proses($tahun='',$param1='',$bulan=''){
        	$sql = "SELECT (SKRK.JUMLAH + IMB.JUMLAH) AS jumlahnya FROM ( SELECT bulan, no_bulan, tahun, COUNT (NO_REGISTRASI) AS JUMLAH FROM ( SELECT DISTINCT * FROM ( SELECT TO_CHAR ( T_FO.TGL_REGISTRASI, 'Month' ) AS Bulan, TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') AS no_bulan, TO_CHAR (T_FO.TGL_REGISTRASI, 'yyyy') AS Tahun, ID_CKTR, REGISTER_ULANG.NO_REGISTRASI, NAMA FROM REGISTER_ULANG, T_FO_REG_ULANG, T_FO WHERE REGISTER_ULANG.NO_REGISTRASI = T_FO_REG_ULANG.NO_REGISTRASI AND REGISTER_ULANG.TGL_REG = T_FO_REG_ULANG.TGL_REGISTRASI AND REGISTER_ULANG.NO_REGISTRASI = T_FO.NO_REGISTRASI AND REGISTER_ULANG.TGL_REG = T_FO.TGL_REGISTRASI AND REGISTER_ULANG.REG_KE IN T_FO_REG_ULANG.REG_KE AND REGISTER_ULANG.PERIJINAN = 'SKRK' AND ID_PAKET = '$param1' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'yyyy') = '$tahun' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') LIKE '%$bulan' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') NOT LIKE '%1$bulan' ) A WHERE ID_CKTR = ( SELECT ID_CKTR FROM ( SELECT * FROM REGISTER_ULANG WHERE REGISTER_ULANG.NO_REGISTRASI = A .NO_REGISTRASI ORDER BY ID_CKTR DESC ) WHERE ROWNUM = 1 ) AND NO_REGISTRASI NOT IN ( SELECT VW_SKRK_DETIL.NO_REGISTRASI FROM VW_SKRK_DETIL, T_FO WHERE VW_SKRK_DETIL.NO_REGISTRASI = T_FO.NO_REGISTRASI AND VW_SKRK_DETIL.TGL_REGISTRASI = T_FO.TGL_REGISTRASI AND VW_SKRK_DETIL.STATUS LIKE 'PENGESAHAN SK' AND TO_CHAR ( VW_SKRK_DETIL.TGL_REGISTRASI, 'yyyy' ) = '$tahun' AND TO_CHAR ( VW_SKRK_DETIL.TGL_REGISTRASI, 'mm' ) LIKE '%$bulan' AND TO_CHAR ( VW_SKRK_DETIL.TGL_REGISTRASI, 'mm' ) NOT LIKE '%1$bulan' AND ID_PAKET = '$param1' ) ORDER BY NO_REGISTRASI ASC ) GROUP BY no_bulan, bulan, tahun ) SKRK, ( SELECT bulan, no_bulan, tahun, COUNT (NO_REGISTRASI) AS JUMLAH FROM ( SELECT DISTINCT * FROM ( SELECT TO_CHAR ( T_FO.TGL_REGISTRASI, 'Month' ) AS Bulan, TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') AS no_bulan, TO_CHAR (T_FO.TGL_REGISTRASI, 'yyyy') AS Tahun, ID_CKTR, REGISTER_ULANG.NO_REGISTRASI, NAMA FROM REGISTER_ULANG, T_FO_REG_ULANG, T_FO WHERE REGISTER_ULANG.NO_REGISTRASI = T_FO_REG_ULANG.NO_REGISTRASI AND REGISTER_ULANG.TGL_REG = T_FO_REG_ULANG.TGL_REGISTRASI AND REGISTER_ULANG.NO_REGISTRASI = T_FO.NO_REGISTRASI AND REGISTER_ULANG.TGL_REG = T_FO.TGL_REGISTRASI AND REGISTER_ULANG.REG_KE IN T_FO_REG_ULANG.REG_KE AND REGISTER_ULANG.PERIJINAN = 'IMB' AND ID_PAKET = '$param1' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'yyyy') = '$tahun' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') LIKE '%$bulan' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') NOT LIKE '%1$bulan' ) A WHERE ID_CKTR = ( SELECT ID_CKTR FROM ( SELECT * FROM REGISTER_ULANG WHERE REGISTER_ULANG.NO_REGISTRASI = A .NO_REGISTRASI ORDER BY ID_CKTR DESC ) WHERE ROWNUM = 1 ) AND NO_REGISTRASI NOT IN ( SELECT VW_IMB_DETIL.NO_REGISTRASI FROM VW_IMB_DETIL, T_FO WHERE VW_IMB_DETIL.NO_REGISTRASI = T_FO.NO_REGISTRASI AND VW_IMB_DETIL.TGL_REGISTRASI = T_FO.TGL_REGISTRASI AND VW_IMB_DETIL.STATUS LIKE 'PENGESAHAN SK' AND TO_CHAR ( VW_IMB_DETIL.TGL_REGISTRASI, 'yyyy' ) = '$tahun' AND TO_CHAR ( VW_IMB_DETIL.TGL_REGISTRASI, 'mm' ) LIKE '%$bulan' AND TO_CHAR ( VW_IMB_DETIL.TGL_REGISTRASI, 'mm' ) NOT LIKE '%1$bulan' AND ID_PAKET = '$param1' ) ORDER BY NO_REGISTRASI ASC ) GROUP BY no_bulan, bulan, tahun ) IMB";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_dasboard_imb_pending($tahun='',$param1='',$bulan=''){
        	$sql = "SELECT (SKRK.JUMLAH + IMB.JUMLAH) AS JUMLAHNYA FROM ( SELECT COUNT (NO_REGISTRASI) AS JUMLAH FROM ( SELECT DISTINCT * FROM ( SELECT TO_CHAR ( T_FO.TGL_REGISTRASI, 'Month' ) AS Bulan, TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') AS no_bulan, TO_CHAR (T_FO.TGL_REGISTRASI, 'yyyy') AS Tahun, ID_CKTR, REGISTER_ULANG.NO_REGISTRASI, NAMA FROM REGISTER_ULANG, T_FO_REG_ULANG, T_FO WHERE REGISTER_ULANG.NO_REGISTRASI = T_FO_REG_ULANG.NO_REGISTRASI AND REGISTER_ULANG.TGL_REG = T_FO_REG_ULANG.TGL_REGISTRASI AND REGISTER_ULANG.NO_REGISTRASI = T_FO.NO_REGISTRASI AND REGISTER_ULANG.TGL_REG = T_FO.TGL_REGISTRASI AND REGISTER_ULANG.REG_KE NOT IN T_FO_REG_ULANG.REG_KE AND REGISTER_ULANG.PERIJINAN = 'SKRK' AND ID_PAKET = '$param1' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'yyyy') = '$tahun' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') LIKE '%$bulan' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') NOT LIKE '%1$bulan' ) A WHERE ID_CKTR = ( SELECT ID_CKTR FROM ( SELECT * FROM REGISTER_ULANG WHERE REGISTER_ULANG.NO_REGISTRASI = A .NO_REGISTRASI ORDER BY ID_CKTR DESC ) WHERE ROWNUM = 1 ) ORDER BY NO_REGISTRASI ASC )) SKRK, ( SELECT COUNT (NO_REGISTRASI) AS JUMLAH FROM ( SELECT DISTINCT * FROM ( SELECT TO_CHAR ( T_FO.TGL_REGISTRASI, 'Month' ) AS Bulan, TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') AS no_bulan, TO_CHAR (T_FO.TGL_REGISTRASI, 'yyyy') AS Tahun, ID_CKTR, REGISTER_ULANG.NO_REGISTRASI, NAMA FROM REGISTER_ULANG, T_FO_REG_ULANG, T_FO WHERE REGISTER_ULANG.NO_REGISTRASI = T_FO_REG_ULANG.NO_REGISTRASI AND REGISTER_ULANG.TGL_REG = T_FO_REG_ULANG.TGL_REGISTRASI AND REGISTER_ULANG.NO_REGISTRASI = T_FO.NO_REGISTRASI AND REGISTER_ULANG.TGL_REG = T_FO.TGL_REGISTRASI AND REGISTER_ULANG.REG_KE NOT IN T_FO_REG_ULANG.REG_KE AND REGISTER_ULANG.PERIJINAN = 'IMB' AND ID_PAKET = '$param1' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'yyyy') = '$tahun' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') LIKE '%$bulan' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') NOT LIKE '%1$bulan' ) A WHERE ID_CKTR = ( SELECT ID_CKTR FROM ( SELECT * FROM REGISTER_ULANG WHERE REGISTER_ULANG.NO_REGISTRASI = A .NO_REGISTRASI ORDER BY ID_CKTR DESC ) WHERE ROWNUM = 1 ) ORDER BY NO_REGISTRASI ASC )) IMB";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_dasboard_imb_selesai($tahun='',$param1='',$bulan=''){
        	$sql = "SELECT (SKRK.JUMLAH + IMB.JUMLAH) AS JUMLAHNYA FROM ( SELECT BULAN, NO_BULAN, TAHUN, COUNT (NO_REGISTRASI) AS JUMLAH FROM ( SELECT TO_CHAR ( VW_SKRK_DETIL.TGL_REGISTRASI, 'Month' ) AS Bulan, TO_CHAR ( VW_SKRK_DETIL.TGL_REGISTRASI, 'mm' ) AS no_bulan, TO_CHAR ( VW_SKRK_DETIL.TGL_REGISTRASI, 'yyyy' ) AS Tahun, VW_SKRK_DETIL.NO_REGISTRASI FROM VW_SKRK_DETIL, T_FO WHERE VW_SKRK_DETIL.NO_REGISTRASI = T_FO.NO_REGISTRASI AND VW_SKRK_DETIL.TGL_REGISTRASI = T_FO.TGL_REGISTRASI AND VW_SKRK_DETIL.STATUS LIKE 'PENGESAHAN SK' AND ID_PAKET = '$param1' AND TO_CHAR ( VW_SKRK_DETIL.TGL_REGISTRASI, 'yyyy' ) = '$tahun' AND TO_CHAR ( VW_SKRK_DETIL.TGL_REGISTRASI, 'mm' ) LIKE '%$bulan' AND TO_CHAR ( VW_SKRK_DETIL.TGL_REGISTRASI, 'mm' ) NOT LIKE '%1$bulan' ) GROUP BY BULAN, NO_BULAN, TAHUN ) SKRK, ( SELECT BULAN, NO_BULAN, TAHUN, COUNT (NO_REGISTRASI) AS JUMLAH FROM ( SELECT TO_CHAR ( VW_IMB_DETIL.TGL_REGISTRASI, 'Month' ) AS Bulan, TO_CHAR ( VW_IMB_DETIL.TGL_REGISTRASI, 'mm' ) AS no_bulan, TO_CHAR ( VW_IMB_DETIL.TGL_REGISTRASI, 'yyyy' ) AS Tahun, VW_IMB_DETIL.NO_REGISTRASI FROM VW_IMB_DETIL, T_FO WHERE VW_IMB_DETIL.NO_REGISTRASI = T_FO.NO_REGISTRASI AND VW_IMB_DETIL.TGL_REGISTRASI = T_FO.TGL_REGISTRASI AND VW_IMB_DETIL.STATUS LIKE 'PENGESAHAN SK' AND ID_PAKET = '$param1' AND TO_CHAR ( VW_IMB_DETIL.TGL_REGISTRASI, 'yyyy' ) = '$tahun' AND TO_CHAR ( VW_IMB_DETIL.TGL_REGISTRASI, 'mm' ) LIKE '%$bulan' AND TO_CHAR ( VW_IMB_DETIL.TGL_REGISTRASI, 'mm' ) NOT LIKE '%1$bulan' ) GROUP BY BULAN, NO_BULAN, TAHUN ) IMB";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_dasboard_imb_tolak($tahun='',$param1='',$bulan=''){
        	$sql = "SELECT (SKRK.JUMLAH + IMB.JUMLAH) AS JUMLAHNYA FROM ( SELECT BULAN, NO_BULAN, TAHUN, COUNT (NO_REGISTRASI) AS JUMLAH FROM ( SELECT TO_CHAR ( VW_SKRK_DETIL.TGL_REGISTRASI, 'Month' ) AS Bulan, TO_CHAR ( VW_SKRK_DETIL.TGL_REGISTRASI, 'mm' ) AS no_bulan, TO_CHAR ( VW_SKRK_DETIL.TGL_REGISTRASI, 'yyyy' ) AS Tahun, VW_SKRK_DETIL.NO_REGISTRASI FROM VW_SKRK_DETIL, T_FO WHERE VW_SKRK_DETIL.NO_REGISTRASI = T_FO.NO_REGISTRASI AND VW_SKRK_DETIL.TGL_REGISTRASI = T_FO.TGL_REGISTRASI AND VW_SKRK_DETIL.STATUS LIKE 'DITOLAK' AND ID_PAKET = '$param1' AND TO_CHAR ( VW_SKRK_DETIL.TGL_REGISTRASI, 'yyyy' ) = '$tahun' AND TO_CHAR ( VW_SKRK_DETIL.TGL_REGISTRASI, 'mm' ) LIKE '%$bulan' AND TO_CHAR ( VW_SKRK_DETIL.TGL_REGISTRASI, 'mm' ) NOT LIKE '%1$bulan' ) GROUP BY BULAN, NO_BULAN, TAHUN ) SKRK, ( SELECT BULAN, NO_BULAN, TAHUN, COUNT (NO_REGISTRASI) AS JUMLAH FROM ( SELECT TO_CHAR ( VW_IMB_DETIL.TGL_REGISTRASI, 'Month' ) AS Bulan, TO_CHAR ( VW_IMB_DETIL.TGL_REGISTRASI, 'mm' ) AS no_bulan, TO_CHAR ( VW_IMB_DETIL.TGL_REGISTRASI, 'yyyy' ) AS Tahun, VW_IMB_DETIL.NO_REGISTRASI FROM VW_IMB_DETIL, T_FO WHERE VW_IMB_DETIL.NO_REGISTRASI = T_FO.NO_REGISTRASI AND VW_IMB_DETIL.TGL_REGISTRASI = T_FO.TGL_REGISTRASI AND VW_IMB_DETIL.STATUS LIKE 'DITOLAK' AND ID_PAKET = '$param1' AND TO_CHAR ( VW_IMB_DETIL.TGL_REGISTRASI, 'yyyy' ) = '$tahun' AND TO_CHAR ( VW_IMB_DETIL.TGL_REGISTRASI, 'mm' ) LIKE '%$bulan' AND TO_CHAR ( VW_IMB_DETIL.TGL_REGISTRASI, 'mm' ) NOT LIKE '%1$bulan' ) GROUP BY BULAN, NO_BULAN, TAHUN ) IMB";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_dasboard_proses($tahun='',$param1='',$bulan=''){
        	$sql = "SELECT COUNT (NM_HEADER) AS jumlahnya FROM ( SELECT DISTINCT T_FO.TGL_REGISTRASI, T_FO.NO_REGISTRASI, SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) AS KD_HEADER, MIJIN.NM_HEADER FROM T_FO, DATA_PEMOHON, MIJIN, M_PAKET_DETAIL, T_FO_SUB_IJIN WHERE T_FO.NO_REGISTRASI = DATA_PEMOHON.NO_REGISTRASI AND TO_CHAR ( DATA_PEMOHON.TGL_REGISTRASI, 'ddmmyyyy' ) = TO_CHAR ( T_FO.TGL_REGISTRASI, 'ddmmyyyy' ) AND SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) = SUBSTR (MIJIN.KD_IJIN, 1, 4) AND SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) = SUBSTR ( T_FO_SUB_IJIN.KD_IJIN, 1, 4 ) AND T_FO.ID_PAKET = '$param1' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'yyyy') = '$tahun' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') LIKE '%$bulan' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') NOT LIKE '%1$bulan' AND MIJIN.NM_HEADER LIKE '%$param2%' AND DATA_PEMOHON.STS_TOLAK IS NULL AND DATA_PEMOHON.NO_SK IS NULL )";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_dasboard_pending($tahun='',$param1='',$bulan=''){
        	$sql = "SELECT COUNT (NM_HEADER) AS jumlahnya FROM ( SELECT DISTINCT T_FO.TGL_REGISTRASI, T_FO.NO_REGISTRASI, SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) AS KD_HEADER, MIJIN.NM_HEADER FROM T_FO, DATA_PEMOHON, MIJIN, M_PAKET_DETAIL WHERE T_FO.NO_REGISTRASI = DATA_PEMOHON.NO_REGISTRASI AND TO_CHAR ( DATA_PEMOHON.TGL_REGISTRASI, 'ddmmyyyy' ) = TO_CHAR ( T_FO.TGL_REGISTRASI, 'ddmmyyyy' ) AND SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) = SUBSTR (MIJIN.KD_IJIN, 1, 4) AND T_FO.ID_PAKET = '$param1' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'yyyy') = '$tahun' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') LIKE '%$bulan' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') NOT LIKE '%1$bulan'AND ID_ALUR_PROSES IN (9) AND DATA_PEMOHON.STS_TOLAK IS NULL)";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_dasboard_selesai($tahun='',$param1='',$bulan=''){
        	$sql = "SELECT COUNT (NM_HEADER) AS jumlahnya FROM ( SELECT DISTINCT T_FO.TGL_REGISTRASI, T_FO.NO_REGISTRASI, SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) AS KD_HEADER, MIJIN.NM_HEADER FROM T_FO, DATA_PEMOHON, MIJIN, M_PAKET_DETAIL, T_FO_SUB_IJIN WHERE T_FO.NO_REGISTRASI = DATA_PEMOHON.NO_REGISTRASI AND TO_CHAR ( DATA_PEMOHON.TGL_REGISTRASI, 'ddmmyyyy' ) = TO_CHAR ( T_FO.TGL_REGISTRASI, 'ddmmyyyy' ) AND SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) = SUBSTR (MIJIN.KD_IJIN, 1, 4) AND SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) = SUBSTR ( T_FO_SUB_IJIN.KD_IJIN, 1, 4 ) AND T_FO.ID_PAKET = '$param1' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'yyyy') = '$tahun' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') LIKE '%$bulan' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') NOT LIKE '%1$bulan'  AND DATA_PEMOHON.STS_TOLAK IS NULL AND DATA_PEMOHON.NO_SK IS NOT NULL )";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_dasboard_tolak($tahun='',$param1='',$bulan=''){
        	$sql = "SELECT COUNT (NM_HEADER) AS jumlahnya FROM ( SELECT DISTINCT T_FO.TGL_REGISTRASI, T_FO.NO_REGISTRASI, SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) AS KD_HEADER, MIJIN.NM_HEADER FROM T_FO, DATA_PEMOHON, MIJIN, M_PAKET_DETAIL WHERE T_FO.NO_REGISTRASI = DATA_PEMOHON.NO_REGISTRASI AND TO_CHAR ( DATA_PEMOHON.TGL_REGISTRASI, 'ddmmyyyy' ) = TO_CHAR ( T_FO.TGL_REGISTRASI, 'ddmmyyyy' ) AND SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) = SUBSTR (MIJIN.KD_IJIN, 1, 4) AND T_FO.ID_PAKET = '$param1' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'yyyy') = '$tahun' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') LIKE '%$bulan' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') NOT LIKE '%1$bulan' AND ID_ALUR_PROSES != 100 AND DATA_PEMOHON.STS_TOLAK IS NOT NULL)";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_dasboard_gabungan_proses($tahun='',$param1='',$bulan=''){
        	$sql = "SELECT ( SKRK.JUMLAH + IMB.JUMLAH + BIASA.JUMLAHNYA ) AS JUMLAHNYA FROM ( SELECT COUNT (NM_HEADER) AS jumlahnya FROM ( SELECT DISTINCT T_FO.TGL_REGISTRASI, T_FO.NO_REGISTRASI, SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) AS KD_HEADER, MIJIN.NM_HEADER FROM T_FO, DATA_PEMOHON, MIJIN, M_PAKET_DETAIL, T_FO_SUB_IJIN WHERE T_FO.NO_REGISTRASI = DATA_PEMOHON.NO_REGISTRASI AND TO_CHAR ( DATA_PEMOHON.TGL_REGISTRASI, 'ddmmyyyy' ) = TO_CHAR ( T_FO.TGL_REGISTRASI, 'ddmmyyyy' ) AND SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) = SUBSTR (MIJIN.KD_IJIN, 1, 4) AND SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) = SUBSTR ( T_FO_SUB_IJIN.KD_IJIN, 1, 4 ) AND T_FO.ID_PAKET = '$param1' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'yyyy') = '$tahun' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') LIKE '%$bulan' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') NOT LIKE '%1$bulan'  AND DATA_PEMOHON.STS_TOLAK IS NULL AND DATA_PEMOHON.NO_SK IS NOT NULL)) BIASA, ( SELECT bulan, no_bulan, tahun, COUNT (NO_REGISTRASI) AS JUMLAH FROM ( SELECT DISTINCT * FROM ( SELECT TO_CHAR ( T_FO.TGL_REGISTRASI, 'Month' ) AS Bulan, TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') AS no_bulan, TO_CHAR (T_FO.TGL_REGISTRASI, 'yyyy') AS Tahun, ID_CKTR, REGISTER_ULANG.NO_REGISTRASI, NAMA FROM REGISTER_ULANG, T_FO_REG_ULANG, T_FO WHERE REGISTER_ULANG.NO_REGISTRASI = T_FO_REG_ULANG.NO_REGISTRASI AND REGISTER_ULANG.TGL_REG = T_FO_REG_ULANG.TGL_REGISTRASI AND REGISTER_ULANG.NO_REGISTRASI = T_FO.NO_REGISTRASI AND REGISTER_ULANG.TGL_REG = T_FO.TGL_REGISTRASI AND REGISTER_ULANG.REG_KE IN T_FO_REG_ULANG.REG_KE AND REGISTER_ULANG.PERIJINAN = 'SKRK' AND ID_PAKET = '$param1' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'yyyy') = '$tahun' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') LIKE '%$bulan' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') NOT LIKE '%1$bulan' ) A WHERE ID_CKTR = ( SELECT ID_CKTR FROM ( SELECT * FROM REGISTER_ULANG WHERE REGISTER_ULANG.NO_REGISTRASI = A .NO_REGISTRASI ORDER BY ID_CKTR DESC ) WHERE ROWNUM = 1 ) AND NO_REGISTRASI NOT IN ( SELECT VW_SKRK_DETIL.NO_REGISTRASI FROM VW_SKRK_DETIL, T_FO WHERE VW_SKRK_DETIL.NO_REGISTRASI = T_FO.NO_REGISTRASI AND VW_SKRK_DETIL.TGL_REGISTRASI = T_FO.TGL_REGISTRASI AND VW_SKRK_DETIL.STATUS LIKE 'PENGESAHAN SK' AND TO_CHAR ( VW_SKRK_DETIL.TGL_REGISTRASI, 'yyyy' ) = '$tahun' AND TO_CHAR ( VW_SKRK_DETIL.TGL_REGISTRASI, 'mm' ) LIKE '%$bulan' AND TO_CHAR ( VW_SKRK_DETIL.TGL_REGISTRASI, 'mm' ) NOT LIKE '%1$bulan' AND ID_PAKET = '$param1' ) ORDER BY NO_REGISTRASI ASC ) GROUP BY no_bulan, bulan, tahun ) SKRK, ( SELECT bulan, no_bulan, tahun, COUNT (NO_REGISTRASI) AS JUMLAH FROM ( SELECT DISTINCT * FROM ( SELECT TO_CHAR ( T_FO.TGL_REGISTRASI, 'Month' ) AS Bulan, TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') AS no_bulan, TO_CHAR (T_FO.TGL_REGISTRASI, 'yyyy') AS Tahun, ID_CKTR, REGISTER_ULANG.NO_REGISTRASI, NAMA FROM REGISTER_ULANG, T_FO_REG_ULANG, T_FO WHERE REGISTER_ULANG.NO_REGISTRASI = T_FO_REG_ULANG.NO_REGISTRASI AND REGISTER_ULANG.TGL_REG = T_FO_REG_ULANG.TGL_REGISTRASI AND REGISTER_ULANG.NO_REGISTRASI = T_FO.NO_REGISTRASI AND REGISTER_ULANG.TGL_REG = T_FO.TGL_REGISTRASI AND REGISTER_ULANG.REG_KE IN T_FO_REG_ULANG.REG_KE AND REGISTER_ULANG.PERIJINAN = 'IMB' AND ID_PAKET = '$param1' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'yyyy') = '$tahun' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') LIKE '%$bulan' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') NOT LIKE '%1$bulan' ) A WHERE ID_CKTR = ( SELECT ID_CKTR FROM ( SELECT * FROM REGISTER_ULANG WHERE REGISTER_ULANG.NO_REGISTRASI = A .NO_REGISTRASI ORDER BY ID_CKTR DESC ) WHERE ROWNUM = 1 ) AND NO_REGISTRASI NOT IN ( SELECT VW_IMB_DETIL.NO_REGISTRASI FROM VW_IMB_DETIL, T_FO WHERE VW_IMB_DETIL.NO_REGISTRASI = T_FO.NO_REGISTRASI AND VW_IMB_DETIL.TGL_REGISTRASI = T_FO.TGL_REGISTRASI AND VW_IMB_DETIL.STATUS LIKE 'PENGESAHAN SK' AND TO_CHAR ( VW_IMB_DETIL.TGL_REGISTRASI, 'yyyy' ) = '$tahun' AND TO_CHAR ( VW_IMB_DETIL.TGL_REGISTRASI, 'mm' ) LIKE '%$bulan' AND TO_CHAR ( VW_IMB_DETIL.TGL_REGISTRASI, 'mm' ) NOT LIKE '%1$bulan' AND ID_PAKET = '$param1' ) ORDER BY NO_REGISTRASI ASC ) GROUP BY no_bulan, bulan, tahun ) IMB";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_dasboard_gabungan_pending($tahun='',$param1='',$bulan=''){
        	$sql = "SELECT ( SKRK.JUMLAH + IMB.JUMLAH + BIASA.JUMLAHNYA ) AS JUMLAHNYA FROM ( SELECT COUNT (NM_HEADER) AS jumlahnya FROM ( SELECT DISTINCT T_FO.TGL_REGISTRASI, T_FO.NO_REGISTRASI, SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) AS KD_HEADER, MIJIN.NM_HEADER FROM T_FO, DATA_PEMOHON, MIJIN, M_PAKET_DETAIL WHERE T_FO.NO_REGISTRASI = DATA_PEMOHON.NO_REGISTRASI AND TO_CHAR ( DATA_PEMOHON.TGL_REGISTRASI, 'ddmmyyyy' ) = TO_CHAR ( T_FO.TGL_REGISTRASI, 'ddmmyyyy' ) AND SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) = SUBSTR (MIJIN.KD_IJIN, 1, 4) AND T_FO.ID_PAKET = '$param1' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'yyyy') = '$tahun' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') LIKE '%$bulan' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') NOT LIKE '%1$bulan' AND ID_ALUR_PROSES IN (9) AND DATA_PEMOHON.STS_TOLAK IS NULL )) BIASA, ( SELECT COUNT (NO_REGISTRASI) AS JUMLAH FROM ( SELECT DISTINCT * FROM ( SELECT TO_CHAR ( T_FO.TGL_REGISTRASI, 'Month' ) AS Bulan, TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') AS no_bulan, TO_CHAR (T_FO.TGL_REGISTRASI, 'yyyy') AS Tahun, ID_CKTR, REGISTER_ULANG.NO_REGISTRASI, NAMA FROM REGISTER_ULANG, T_FO_REG_ULANG, T_FO WHERE REGISTER_ULANG.NO_REGISTRASI = T_FO_REG_ULANG.NO_REGISTRASI AND REGISTER_ULANG.TGL_REG = T_FO_REG_ULANG.TGL_REGISTRASI AND REGISTER_ULANG.NO_REGISTRASI = T_FO.NO_REGISTRASI AND REGISTER_ULANG.TGL_REG = T_FO.TGL_REGISTRASI AND REGISTER_ULANG.REG_KE NOT IN T_FO_REG_ULANG.REG_KE AND REGISTER_ULANG.PERIJINAN = 'SKRK' AND ID_PAKET = '$param1' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'yyyy') = '$tahun' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') LIKE '%$bulan' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') NOT LIKE '%1$bulan' ) A WHERE ID_CKTR = ( SELECT ID_CKTR FROM ( SELECT * FROM REGISTER_ULANG WHERE REGISTER_ULANG.NO_REGISTRASI = A .NO_REGISTRASI ORDER BY ID_CKTR DESC ) WHERE ROWNUM = 1 ) ORDER BY NO_REGISTRASI ASC )) SKRK, ( SELECT COUNT (NO_REGISTRASI) AS JUMLAH FROM ( SELECT DISTINCT * FROM ( SELECT TO_CHAR ( T_FO.TGL_REGISTRASI, 'Month' ) AS Bulan, TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') AS no_bulan, TO_CHAR (T_FO.TGL_REGISTRASI, 'yyyy') AS Tahun, ID_CKTR, REGISTER_ULANG.NO_REGISTRASI, NAMA FROM REGISTER_ULANG, T_FO_REG_ULANG, T_FO WHERE REGISTER_ULANG.NO_REGISTRASI = T_FO_REG_ULANG.NO_REGISTRASI AND REGISTER_ULANG.TGL_REG = T_FO_REG_ULANG.TGL_REGISTRASI AND REGISTER_ULANG.NO_REGISTRASI = T_FO.NO_REGISTRASI AND REGISTER_ULANG.TGL_REG = T_FO.TGL_REGISTRASI AND REGISTER_ULANG.REG_KE NOT IN T_FO_REG_ULANG.REG_KE AND REGISTER_ULANG.PERIJINAN = 'IMB' AND ID_PAKET = '$param1' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'yyyy') = '$tahun' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') LIKE '%$bulan' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') NOT LIKE '%1$bulan' ) A WHERE ID_CKTR = ( SELECT ID_CKTR FROM ( SELECT * FROM REGISTER_ULANG WHERE REGISTER_ULANG.NO_REGISTRASI = A .NO_REGISTRASI ORDER BY ID_CKTR DESC ) WHERE ROWNUM = 1 ) ORDER BY NO_REGISTRASI ASC )) IMB";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_dasboard_gabungan_selesai($tahun='',$param1='',$bulan=''){
        	$sql = "SELECT ( SKRK.JUMLAH + IMB.JUMLAH + BIASA.JUMLAHNYA ) AS JUMLAHNYA FROM (SELECT COUNT (NM_HEADER) AS jumlahnya FROM ( SELECT DISTINCT T_FO.TGL_REGISTRASI, T_FO.NO_REGISTRASI, SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) AS KD_HEADER, MIJIN.NM_HEADER FROM T_FO, DATA_PEMOHON, MIJIN, M_PAKET_DETAIL, T_FO_SUB_IJIN WHERE T_FO.NO_REGISTRASI = DATA_PEMOHON.NO_REGISTRASI AND TO_CHAR ( DATA_PEMOHON.TGL_REGISTRASI, 'ddmmyyyy' ) = TO_CHAR ( T_FO.TGL_REGISTRASI, 'ddmmyyyy' ) AND SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) = SUBSTR (MIJIN.KD_IJIN, 1, 4) AND SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) = SUBSTR ( T_FO_SUB_IJIN.KD_IJIN, 1, 4 ) AND T_FO.ID_PAKET = '$param1' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'yyyy') = '$tahun' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') LIKE '%$bulan' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') NOT LIKE '%1$bulan'  AND DATA_PEMOHON.STS_TOLAK IS NULL AND DATA_PEMOHON.NO_SK IS NOT NULL)) BIASA, ( SELECT BULAN, NO_BULAN, TAHUN, COUNT (NO_REGISTRASI) AS JUMLAH FROM ( SELECT TO_CHAR ( VW_SKRK_DETIL.TGL_REGISTRASI, 'Month' ) AS Bulan, TO_CHAR ( VW_SKRK_DETIL.TGL_REGISTRASI, 'mm' ) AS no_bulan, TO_CHAR ( VW_SKRK_DETIL.TGL_REGISTRASI, 'yyyy' ) AS Tahun, VW_SKRK_DETIL.NO_REGISTRASI FROM VW_SKRK_DETIL, T_FO WHERE VW_SKRK_DETIL.NO_REGISTRASI = T_FO.NO_REGISTRASI AND VW_SKRK_DETIL.TGL_REGISTRASI = T_FO.TGL_REGISTRASI AND VW_SKRK_DETIL.STATUS LIKE 'PENGESAHAN SK' AND ID_PAKET = '$param1' AND TO_CHAR ( VW_SKRK_DETIL.TGL_REGISTRASI, 'yyyy' ) = '$tahun' AND TO_CHAR ( VW_SKRK_DETIL.TGL_REGISTRASI, 'mm' ) LIKE '%$bulan' AND TO_CHAR ( VW_SKRK_DETIL.TGL_REGISTRASI, 'mm' ) NOT LIKE '%1$bulan' ) GROUP BY BULAN, NO_BULAN, TAHUN ) SKRK, ( SELECT BULAN, NO_BULAN, TAHUN, COUNT (NO_REGISTRASI) AS JUMLAH FROM ( SELECT TO_CHAR ( VW_IMB_DETIL.TGL_REGISTRASI, 'Month' ) AS Bulan, TO_CHAR ( VW_IMB_DETIL.TGL_REGISTRASI, 'mm' ) AS no_bulan, TO_CHAR ( VW_IMB_DETIL.TGL_REGISTRASI, 'yyyy' ) AS Tahun, VW_IMB_DETIL.NO_REGISTRASI FROM VW_IMB_DETIL, T_FO WHERE VW_IMB_DETIL.NO_REGISTRASI = T_FO.NO_REGISTRASI AND VW_IMB_DETIL.TGL_REGISTRASI = T_FO.TGL_REGISTRASI AND VW_IMB_DETIL.STATUS LIKE 'PENGESAHAN SK' AND ID_PAKET = '$param1' AND TO_CHAR ( VW_IMB_DETIL.TGL_REGISTRASI, 'yyyy' ) = '$tahun' AND TO_CHAR ( VW_IMB_DETIL.TGL_REGISTRASI, 'mm' ) LIKE '%$bulan' AND TO_CHAR ( VW_IMB_DETIL.TGL_REGISTRASI, 'mm' ) NOT LIKE '%1$bulan' ) GROUP BY BULAN, NO_BULAN, TAHUN ) IMB";

			$query = $this->db->query($sql);
			return $query->result();
        }
         function get_dasboard_gabungan_tolak($tahun='',$param1='',$bulan=''){
        	$sql = "SELECT ( SKRK.JUMLAH + IMB.JUMLAH + BIASA.JUMLAHNYA ) AS JUMLAHNYA FROM ( SELECT COUNT (NM_HEADER) AS jumlahnya FROM ( SELECT DISTINCT T_FO.TGL_REGISTRASI, T_FO.NO_REGISTRASI, SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) AS KD_HEADER, MIJIN.NM_HEADER FROM T_FO, DATA_PEMOHON, MIJIN, M_PAKET_DETAIL WHERE T_FO.NO_REGISTRASI = DATA_PEMOHON.NO_REGISTRASI AND TO_CHAR ( DATA_PEMOHON.TGL_REGISTRASI, 'ddmmyyyy' ) = TO_CHAR ( T_FO.TGL_REGISTRASI, 'ddmmyyyy' ) AND SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) = SUBSTR (MIJIN.KD_IJIN, 1, 4) AND T_FO.ID_PAKET = '$param1' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'yyyy') = '$tahun' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') LIKE '%$bulan' AND TO_CHAR (T_FO.TGL_REGISTRASI, 'mm') NOT LIKE '%1$bulan' AND ID_ALUR_PROSES != 100 AND DATA_PEMOHON.STS_TOLAK IS NOT NULL )) BIASA, ( SELECT BULAN, NO_BULAN, TAHUN, COUNT (NO_REGISTRASI) AS JUMLAH FROM ( SELECT TO_CHAR ( VW_SKRK_DETIL.TGL_REGISTRASI, 'Month' ) AS Bulan, TO_CHAR ( VW_SKRK_DETIL.TGL_REGISTRASI, 'mm' ) AS no_bulan, TO_CHAR ( VW_SKRK_DETIL.TGL_REGISTRASI, 'yyyy' ) AS Tahun, VW_SKRK_DETIL.NO_REGISTRASI FROM VW_SKRK_DETIL, T_FO WHERE VW_SKRK_DETIL.NO_REGISTRASI = T_FO.NO_REGISTRASI AND VW_SKRK_DETIL.TGL_REGISTRASI = T_FO.TGL_REGISTRASI AND VW_SKRK_DETIL.STATUS LIKE 'DITOLAK' AND ID_PAKET = '$param1' AND TO_CHAR ( VW_SKRK_DETIL.TGL_REGISTRASI, 'yyyy' ) = '$tahun' AND TO_CHAR ( VW_SKRK_DETIL.TGL_REGISTRASI, 'mm' ) LIKE '%$bulan' AND TO_CHAR ( VW_SKRK_DETIL.TGL_REGISTRASI, 'mm' ) NOT LIKE '%1$bulan' ) GROUP BY BULAN, NO_BULAN, TAHUN ) SKRK, ( SELECT BULAN, NO_BULAN, TAHUN, COUNT (NO_REGISTRASI) AS JUMLAH FROM ( SELECT TO_CHAR ( VW_IMB_DETIL.TGL_REGISTRASI, 'Month' ) AS Bulan, TO_CHAR ( VW_IMB_DETIL.TGL_REGISTRASI, 'mm' ) AS no_bulan, TO_CHAR ( VW_IMB_DETIL.TGL_REGISTRASI, 'yyyy' ) AS Tahun, VW_IMB_DETIL.NO_REGISTRASI FROM VW_IMB_DETIL, T_FO WHERE VW_IMB_DETIL.NO_REGISTRASI = T_FO.NO_REGISTRASI AND VW_IMB_DETIL.TGL_REGISTRASI = T_FO.TGL_REGISTRASI AND VW_IMB_DETIL.STATUS LIKE 'DITOLAK' AND ID_PAKET = '$param1' AND TO_CHAR ( VW_IMB_DETIL.TGL_REGISTRASI, 'yyyy' ) = '$tahun' AND TO_CHAR ( VW_IMB_DETIL.TGL_REGISTRASI, 'mm' ) LIKE '%$bulan' AND TO_CHAR ( VW_IMB_DETIL.TGL_REGISTRASI, 'mm' ) NOT LIKE '%1$bulan' ) GROUP BY BULAN, NO_BULAN, TAHUN ) IMB";

			$query = $this->db->query($sql);
			return $query->result();
        }
    	function get_tanggal($tgl1 ='',$tgl2 ='',$param1=''){
        	$sql = "SELECT NM_HEADER, COUNT (NM_HEADER) AS JUMLAH FROM ( SELECT DISTINCT T_FO.TGL_REGISTRASI, T_FO.NO_REGISTRASI, SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) AS KD_HEADER, MIJIN.NM_HEADER FROM T_FO, DATA_PEMOHON, MIJIN, M_PAKET_DETAIL, T_FO_SUB_IJIN WHERE T_FO.NO_REGISTRASI = DATA_PEMOHON.NO_REGISTRASI AND TO_CHAR ( DATA_PEMOHON.TGL_REGISTRASI, 'ddmmyyyy' ) = TO_CHAR ( T_FO.TGL_REGISTRASI, 'ddmmyyyy' ) AND SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) = SUBSTR (MIJIN.KD_IJIN, 1, 4) AND SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) = SUBSTR ( T_FO_SUB_IJIN.KD_IJIN, 1, 4 ) AND T_FO.ID_PAKET = '$param1' AND T_FO.TGL_REGISTRASI BETWEEN TO_DATE ('$tgl1', 'yyyy-mm-dd') AND TO_DATE ('$tgl2', 'yyyy-mm-dd')) WHERE NM_HEADER IS NOT NULL GROUP BY NM_HEADER";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_tanggal_imb($tgl1 ='',$tgl2 ='',$param1=''){
        	$sql = "SELECT NM_HEADER, COUNT (NM_HEADER) AS JUMLAH FROM (	SELECT T_FO.TGL_REGISTRASI, T_FO.NO_REGISTRASI,T_FO_SUB_IJIN.KD_IJIN,MIJIN.NM_HEADER FROM T_FO,T_FO_SUB_IJIN,MIJIN,	M_PAKET_DETAIL WHERE T_FO.NO_REGISTRASI = T_FO_SUB_IJIN.NO_REGISTRASI AND T_FO.TGL_REGISTRASI = T_FO_SUB_IJIN.TGL_REGISTRASI AND T_FO_SUB_IJIN.KD_IJIN = MIJIN.KD_IJIN AND T_FO.ID_PAKET = M_PAKET_DETAIL.KD_PAKET AND SUBSTR (T_FO_SUB_IJIN.KD_IJIN1, 1, 4) = M_PAKET_DETAIL.KD_IJIN_HEADER AND T_FO.TGL_REGISTRASI BETWEEN TO_DATE ('$tgl1', 'yyyy-mm-dd') AND TO_DATE ('$tgl2', 'yyyy-mm-dd') AND T_FO.ID_PAKET = '$param1')GROUP BY NM_HEADER ORDER BY	NM_HEADER ASC";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_tanggal_imb_gabungan($tgl1 ='',$tgl2 ='',$param1=''){
        	$sql = "SELECT NM_HEADER, COUNT (NM_HEADER) AS JUMLAH FROM ( SELECT T_FO.TGL_REGISTRASI, T_FO.NO_REGISTRASI, T_FO_SUB_IJIN.KD_IJIN, MIJIN.NM_HEADER FROM T_FO, T_FO_SUB_IJIN, MIJIN, M_PAKET_DETAIL WHERE T_FO.NO_REGISTRASI = T_FO_SUB_IJIN.NO_REGISTRASI AND T_FO.TGL_REGISTRASI = T_FO_SUB_IJIN.TGL_REGISTRASI AND T_FO_SUB_IJIN.KD_IJIN = MIJIN.KD_IJIN AND T_FO.ID_PAKET = M_PAKET_DETAIL.KD_PAKET AND SUBSTR (T_FO_SUB_IJIN.KD_IJIN1, 1, 4) = M_PAKET_DETAIL.KD_IJIN_HEADER AND T_FO.TGL_REGISTRASI BETWEEN TO_DATE ('$tgl1', 'yyyy-mm-dd') AND TO_DATE ('$tgl2', 'yyyy-mm-dd') AND T_FO.ID_PAKET = '$param1' ) GROUP BY NM_HEADER";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_tanggal_selesai($tgl1 ='',$tgl2 ='',$param1='',$param2=''){
        	$sql = "SELECT NM_HEADER, COUNT (NM_HEADER) AS SELESAI FROM ( SELECT DISTINCT T_FO.TGL_REGISTRASI, T_FO.NO_REGISTRASI, SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) AS KD_HEADER, MIJIN.NM_HEADER FROM T_FO, DATA_PEMOHON, MIJIN, M_PAKET_DETAIL, T_FO_SUB_IJIN WHERE T_FO.NO_REGISTRASI = DATA_PEMOHON.NO_REGISTRASI AND TO_CHAR ( DATA_PEMOHON.TGL_REGISTRASI, 'ddmmyyyy' ) = TO_CHAR ( T_FO.TGL_REGISTRASI, 'ddmmyyyy' ) AND SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) = SUBSTR (MIJIN.KD_IJIN, 1, 4) AND SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) = SUBSTR ( T_FO_SUB_IJIN.KD_IJIN, 1, 4 ) AND T_FO.ID_PAKET = '$param1' AND T_FO.TGL_REGISTRASI BETWEEN TO_DATE ('$tgl1', 'yyyy-mm-dd') AND TO_DATE ('$tgl2', 'yyyy-mm-dd') AND MIJIN.NM_HEADER LIKE '%$param2%' AND DATA_PEMOHON.STS_TOLAK IS NULL AND DATA_PEMOHON.NO_SK IS NOT NULL ) GROUP BY NM_HEADER";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_tanggal_proses($tgl1 ='',$tgl2 ='',$param1='',$param2=''){
        	$sql = "SELECT NM_HEADER, COUNT (NM_HEADER) AS PROSES FROM ( SELECT DISTINCT T_FO.TGL_REGISTRASI, T_FO.NO_REGISTRASI, SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) AS KD_HEADER, MIJIN.NM_HEADER FROM T_FO, DATA_PEMOHON, MIJIN, M_PAKET_DETAIL, T_FO_SUB_IJIN WHERE T_FO.NO_REGISTRASI = DATA_PEMOHON.NO_REGISTRASI AND TO_CHAR ( DATA_PEMOHON.TGL_REGISTRASI, 'ddmmyyyy' ) = TO_CHAR ( T_FO.TGL_REGISTRASI, 'ddmmyyyy' ) AND SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) = SUBSTR (MIJIN.KD_IJIN, 1, 4) AND SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) = SUBSTR ( T_FO_SUB_IJIN.KD_IJIN, 1, 4 ) AND T_FO.ID_PAKET = '$param1' AND T_FO.TGL_REGISTRASI BETWEEN TO_DATE ('$tgl1', 'yyyy-mm-dd') AND TO_DATE ('$tgl2', 'yyyy-mm-dd') AND MIJIN.NM_HEADER LIKE '%$param2%' AND DATA_PEMOHON.STS_TOLAK IS NULL AND DATA_PEMOHON.NO_SK IS NULL ) GROUP BY NM_HEADER";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_tanggal_pending($tgl1 ='',$tgl2 ='',$param1='',$param2=''){
        	$sql = "SELECT NM_HEADER, COUNT (NM_HEADER) AS PENDING FROM ( SELECT DISTINCT T_FO.TGL_REGISTRASI, T_FO.NO_REGISTRASI, SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) AS KD_HEADER, MIJIN.NM_HEADER FROM T_FO, DATA_PEMOHON, MIJIN, M_PAKET_DETAIL, T_FO_SUB_IJIN WHERE T_FO.NO_REGISTRASI = DATA_PEMOHON.NO_REGISTRASI AND TO_CHAR ( DATA_PEMOHON.TGL_REGISTRASI, 'ddmmyyyy' ) = TO_CHAR ( T_FO.TGL_REGISTRASI, 'ddmmyyyy' ) AND SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) = SUBSTR (MIJIN.KD_IJIN, 1, 4) AND SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) = SUBSTR ( T_FO_SUB_IJIN.KD_IJIN, 1, 4 ) AND T_FO.ID_PAKET = '$param1' AND T_FO.TGL_REGISTRASI BETWEEN TO_DATE ('$tgl1', 'yyyy-mm-dd') AND TO_DATE ('$tgl2', 'yyyy-mm-dd') AND T_FO_SUB_IJIN.ID_ALUR_PROSES IN (9) AND MIJIN.NM_HEADER LIKE '%$param2%' AND DATA_PEMOHON.STS_TOLAK IS NULL AND DATA_PEMOHON.NO_SK IS NULL  ) GROUP BY NM_HEADER";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_tanggal_tolak($tgl1 ='',$tgl2 ='',$param1='',$param2=''){
        	$sql = "SELECT NM_HEADER, COUNT (NM_HEADER) AS TOLAK FROM ( SELECT DISTINCT	T_FO.TGL_REGISTRASI,T_FO.NO_REGISTRASI,
			SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) AS KD_HEADER, MIJIN.NM_HEADER FROM T_FO, DATA_PEMOHON, MIJIN, M_PAKET_DETAIL WHERE
			T_FO.NO_REGISTRASI = DATA_PEMOHON.NO_REGISTRASI	AND TO_CHAR (DATA_PEMOHON.TGL_REGISTRASI,'ddmmyyyy') = TO_CHAR (T_FO.TGL_REGISTRASI,'ddmmyyyy')	AND SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) = SUBSTR (MIJIN.KD_IJIN, 1, 4) AND T_FO.ID_PAKET = '$param1' AND T_FO.TGL_REGISTRASI BETWEEN TO_DATE ('$tgl1', 'yyyy-mm-dd') AND TO_DATE ('$tgl2', 'yyyy-mm-dd') AND ID_ALUR_PROSES != 100 and NM_HEADER like '%$param2%' AND DATA_PEMOHON.STS_TOLAK IS NOT NULL) GROUP BY NM_HEADER";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_selesai_imb_skrk($tgl1 ='',$tgl2 ='',$param1='',$param2=''){
        	$sql = "SELECT COUNT( VW_".$param2."_DETIL.NO_REGISTRASI ) AS jumlah FROM VW_".$param2."_DETIL,T_FO WHERE VW_".$param2."_DETIL.NO_REGISTRASI = T_FO.NO_REGISTRASI AND VW_".$param2."_DETIL.TGL_REGISTRASI = T_FO.TGL_REGISTRASI AND VW_".$param2."_DETIL.STATUS LIKE 'PENGESAHAN SK' AND VW_".$param2."_DETIL.TGL_REGISTRASI BETWEEN TO_DATE( '$tgl1', 'yyyy-mm-dd' ) AND TO_DATE( '$tgl2', 'yyyy-mm-dd' ) AND ID_PAKET = '$param1'";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_tolak_imb_skrk($tgl1 ='',$tgl2 ='',$param1='',$param2=''){
        	$sql = "SELECT COUNT( VW_".$param2."_DETIL.NO_REGISTRASI ) AS jumlah FROM VW_".$param2."_DETIL,T_FO WHERE VW_".$param2."_DETIL.NO_REGISTRASI = T_FO.NO_REGISTRASI AND VW_".$param2."_DETIL.TGL_REGISTRASI = T_FO.TGL_REGISTRASI AND VW_".$param2."_DETIL.STATUS LIKE 'DITOLAK' AND VW_".$param2."_DETIL.TGL_REGISTRASI BETWEEN TO_DATE( '$tgl1', 'yyyy-mm-dd' ) AND TO_DATE( '$tgl2', 'yyyy-mm-dd' ) AND ID_PAKET = '$param1'";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_proses_imb_skrk($tgl1 ='',$tgl2 ='',$param1='',$param2=""){
        	$sql = "SELECT COUNT (NO_REGISTRASI) AS JUMLAH FROM ( SELECT DISTINCT * FROM ( SELECT ID_CKTR, REGISTER_ULANG.NO_REGISTRASI, NAMA FROM REGISTER_ULANG, T_FO_REG_ULANG, T_FO WHERE REGISTER_ULANG.NO_REGISTRASI = T_FO_REG_ULANG.NO_REGISTRASI AND REGISTER_ULANG.TGL_REG = T_FO_REG_ULANG.TGL_REGISTRASI AND REGISTER_ULANG.NO_REGISTRASI = T_FO.NO_REGISTRASI AND REGISTER_ULANG.TGL_REG = T_FO.TGL_REGISTRASI AND REGISTER_ULANG.REG_KE IN T_FO_REG_ULANG.REG_KE AND TGL_REG BETWEEN TO_DATE ( '$tgl1', ' yyyy-mm-dd ' ) AND TO_DATE ( '$tgl2', ' yyyy-mm-dd ' ) AND REGISTER_ULANG.PERIJINAN = '$param2' AND ID_PAKET = '$param1' ) A WHERE ID_CKTR = ( SELECT ID_CKTR FROM ( SELECT * FROM REGISTER_ULANG WHERE REGISTER_ULANG.NO_REGISTRASI = A .NO_REGISTRASI ORDER BY ID_CKTR DESC ) WHERE ROWNUM = 1 ) AND NO_REGISTRASI NOT IN ( SELECT VW_".$param2."_DETIL.NO_REGISTRASI FROM VW_".$param2."_DETIL, T_FO WHERE VW_".$param2."_DETIL.NO_REGISTRASI = T_FO.NO_REGISTRASI AND VW_".$param2."_DETIL.TGL_REGISTRASI = T_FO.TGL_REGISTRASI AND VW_".$param2."_DETIL.STATUS LIKE 'PENGESAHAN SK' AND VW_".$param2."_DETIL.TGL_REGISTRASI BETWEEN TO_DATE ('$tgl1', 'yyyy-mm-dd') AND TO_DATE ( '$tgl2', 'yyyy-mm-dd ' ) AND ID_PAKET = '$param1' ) ORDER BY NO_REGISTRASI ASC )";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_pending_imb_skrk($tgl1 ='',$tgl2 ='',$param1='',$param2=""){
        	$sql = "SELECT COUNT( NO_REGISTRASI ) AS JUMLAH FROM (SELECT DISTINCT * FROM(SELECT ID_CKTR,REGISTER_ULANG.NO_REGISTRASI,NAMA FROM REGISTER_ULANG,T_FO_REG_ULANG,T_FO WHERE REGISTER_ULANG.NO_REGISTRASI = T_FO_REG_ULANG.NO_REGISTRASI AND REGISTER_ULANG.TGL_REG = T_FO_REG_ULANG.TGL_REGISTRASI AND REGISTER_ULANG.NO_REGISTRASI = T_FO.NO_REGISTRASI AND REGISTER_ULANG.TGL_REG = T_FO.TGL_REGISTRASI AND REGISTER_ULANG.REG_KE NOT IN T_FO_REG_ULANG.REG_KE AND TGL_REG BETWEEN TO_DATE( '$tgl1', 'yyyy-mm-dd' ) AND TO_DATE( '$tgl2', 'yyyy-mm-dd' ) AND REGISTER_ULANG.PERIJINAN = '$param2' AND ID_PAKET = '$param1') a WHERE ID_CKTR = ( SELECT ID_CKTR FROM ( SELECT * FROM REGISTER_ULANG WHERE REGISTER_ULANG.NO_REGISTRASI = a.NO_REGISTRASI ORDER BY ID_CKTR DESC ) WHERE ROWNUM = 1 ) ORDER BY NO_REGISTRASI ASC)";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_selesai_imb_skrk_detail($tgl1 ='',$tgl2 ='',$param1='',$param2=''){
        	$sql = "SELECT * FROM VW_".$param2."_DETIL,T_FO WHERE VW_".$param2."_DETIL.NO_REGISTRASI = T_FO.NO_REGISTRASI AND VW_".$param2."_DETIL.TGL_REGISTRASI = T_FO.TGL_REGISTRASI AND VW_".$param2."_DETIL.STATUS LIKE 'PENGESAHAN SK' AND VW_".$param2."_DETIL.TGL_REGISTRASI BETWEEN TO_DATE( '$tgl1', 'yyyy-mm-dd' ) AND TO_DATE( '$tgl2', 'yyyy-mm-dd' ) AND ID_PAKET = '$param1' ORDER BY T_FO.NO_REGISTRASI";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_tolak_imb_skrk_detail($tgl1 ='',$tgl2 ='',$param1='',$param2=''){
        	$sql = "SELECT * FROM VW_".$param2."_DETIL,T_FO WHERE VW_".$param2."_DETIL.NO_REGISTRASI = T_FO.NO_REGISTRASI AND VW_".$param2."_DETIL.TGL_REGISTRASI = T_FO.TGL_REGISTRASI AND VW_".$param2."_DETIL.STATUS LIKE 'DITOLAK' AND VW_".$param2."_DETIL.TGL_REGISTRASI BETWEEN TO_DATE( '$tgl1', 'yyyy-mm-dd' ) AND TO_DATE( '$tgl2', 'yyyy-mm-dd' ) AND ID_PAKET = '$param1' ORDER BY T_FO.NO_REGISTRASI";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_proses_imb_skrk_detail($tgl1 ='',$tgl2 ='',$param1='',$param2=""){
        	$sql = "SELECT DISTINCT * FROM (SELECT REGISTER_ULANG.NO_REGISTRASI,T_FO.TGL_REGISTRASI,NAMA,ALAMAT,NAMA_PERUSAHAAN, ALAMAT_PT,ID_CKTR FROM REGISTER_ULANG, T_FO_REG_ULANG, T_FO WHERE REGISTER_ULANG.NO_REGISTRASI = T_FO_REG_ULANG.NO_REGISTRASI AND REGISTER_ULANG.TGL_REG = T_FO_REG_ULANG.TGL_REGISTRASI AND REGISTER_ULANG.NO_REGISTRASI = T_FO.NO_REGISTRASI AND REGISTER_ULANG.TGL_REG = T_FO.TGL_REGISTRASI AND REGISTER_ULANG.REG_KE IN T_FO_REG_ULANG.REG_KE AND TGL_REG BETWEEN TO_DATE( '$tgl1', 'yyyy-mm-dd' ) AND TO_DATE( '$tgl2', 'yyyy-mm-dd' ) AND REGISTER_ULANG.PERIJINAN = '$param2' AND ID_PAKET = '$param1') a WHERE ID_CKTR = ( SELECT ID_CKTR FROM ( SELECT * FROM REGISTER_ULANG WHERE REGISTER_ULANG.NO_REGISTRASI = a.NO_REGISTRASI ORDER BY ID_CKTR DESC ) WHERE ROWNUM = 1 ) AND NO_REGISTRASI NOT IN ( SELECT VW_".$param2."_DETIL.NO_REGISTRASI FROM VW_".$param2."_DETIL, T_FO WHERE VW_".$param2."_DETIL.NO_REGISTRASI = T_FO.NO_REGISTRASI AND VW_".$param2."_DETIL.TGL_REGISTRASI = T_FO.TGL_REGISTRASI AND VW_".$param2."_DETIL.STATUS LIKE 'PENGESAHAN SK' AND VW_".$param2."_DETIL.TGL_REGISTRASI BETWEEN TO_DATE ('$tgl1', 'yyyy-mm-dd') AND TO_DATE ( '$tgl2', 'yyyy-mm-dd ' ) AND ID_PAKET = '$param1' )ORDER BY a.NO_REGISTRASI ASC";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_pending_imb_skrk_detail($tgl1 ='',$tgl2 ='',$param1='',$param2=""){
        	$sql = "SELECT DISTINCT * FROM (SELECT REGISTER_ULANG.NO_REGISTRASI,T_FO.TGL_REGISTRASI,NAMA,ALAMAT,NAMA_PERUSAHAAN, ALAMAT_PT,ID_CKTR FROM REGISTER_ULANG, T_FO_REG_ULANG, T_FO WHERE REGISTER_ULANG.NO_REGISTRASI = T_FO_REG_ULANG.NO_REGISTRASI AND REGISTER_ULANG.TGL_REG = T_FO_REG_ULANG.TGL_REGISTRASI AND REGISTER_ULANG.NO_REGISTRASI = T_FO.NO_REGISTRASI AND REGISTER_ULANG.TGL_REG = T_FO.TGL_REGISTRASI AND REGISTER_ULANG.REG_KE NOT IN T_FO_REG_ULANG.REG_KE AND TGL_REG BETWEEN TO_DATE( '$tgl1', 'yyyy-mm-dd' ) AND TO_DATE( '$tgl2', 'yyyy-mm-dd' ) AND REGISTER_ULANG.PERIJINAN = '$param2' AND ID_PAKET = '$param1') a WHERE ID_CKTR = ( SELECT ID_CKTR FROM ( SELECT * FROM REGISTER_ULANG WHERE REGISTER_ULANG.NO_REGISTRASI = a.NO_REGISTRASI ORDER BY ID_CKTR DESC ) WHERE ROWNUM = 1 ) ORDER BY a.NO_REGISTRASI ASC";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_tanggal_proses_detail($tgl1 ='',$tgl2 ='',$param1='',$param2=''){
        	$sql = "SELECT * FROM ( SELECT DISTINCT T_FO.TGL_REGISTRASI, T_FO.NO_REGISTRASI, NAMA, ALAMAT, NAMA_PERUSAHAAN, ALAMAT_PT, SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) AS KD_HEADER, MIJIN.NM_HEADER FROM T_FO, DATA_PEMOHON, MIJIN, M_PAKET_DETAIL, T_FO_SUB_IJIN WHERE T_FO.NO_REGISTRASI = DATA_PEMOHON.NO_REGISTRASI AND TO_CHAR ( DATA_PEMOHON.TGL_REGISTRASI, 'ddmmyyyy' ) = TO_CHAR ( T_FO.TGL_REGISTRASI, 'ddmmyyyy' ) AND SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) = SUBSTR (MIJIN.KD_IJIN, 1, 4) AND SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) = SUBSTR ( T_FO_SUB_IJIN.KD_IJIN, 1, 4 ) AND T_FO.ID_PAKET = '$param1' AND T_FO.TGL_REGISTRASI BETWEEN TO_DATE ('$tgl1', 'yyyy-mm-dd') AND TO_DATE ('$tgl2', 'yyyy-mm-dd')AND MIJIN.NM_HEADER LIKE '%$param2%' AND DATA_PEMOHON.STS_TOLAK IS NULL AND DATA_PEMOHON.NO_SK IS NULL ) ORDER BY NO_REGISTRASI ASC";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_tanggal_pending_detail($tgl1 ='',$tgl2 ='',$param1='',$param2=''){
        	$sql = "SELECT * FROM ( SELECT DISTINCT T_FO.TGL_REGISTRASI, T_FO.NO_REGISTRASI, NAMA, ALAMAT, NAMA_PERUSAHAAN, ALAMAT_PT, SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) AS KD_HEADER, MIJIN.NM_HEADER FROM T_FO, DATA_PEMOHON, MIJIN, M_PAKET_DETAIL, T_FO_SUB_IJIN WHERE T_FO.NO_REGISTRASI = DATA_PEMOHON.NO_REGISTRASI AND TO_CHAR ( DATA_PEMOHON.TGL_REGISTRASI, 'ddmmyyyy' ) = TO_CHAR ( T_FO.TGL_REGISTRASI, 'ddmmyyyy' ) AND SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) = SUBSTR (MIJIN.KD_IJIN, 1, 4) AND SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) = SUBSTR ( T_FO_SUB_IJIN.KD_IJIN, 1, 4 ) AND T_FO.ID_PAKET = '$param1' AND T_FO.TGL_REGISTRASI BETWEEN TO_DATE ('$tgl1', 'yyyy-mm-dd') AND TO_DATE ('$tgl2', 'yyyy-mm-dd') AND T_FO_SUB_IJIN.ID_ALUR_PROSES IN (9) AND MIJIN.NM_HEADER LIKE '%$param2%' AND DATA_PEMOHON.STS_TOLAK IS NULL ) ORDER BY NO_REGISTRASI ASC";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_tanggal_selesai_detail($tgl1 ='',$tgl2 ='',$param1='',$param2=''){
        	$sql = "SELECT * FROM ( SELECT DISTINCT T_FO.TGL_REGISTRASI, T_FO.NO_REGISTRASI, NAMA, ALAMAT, NAMA_PERUSAHAAN, ALAMAT_PT, SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) AS KD_HEADER, MIJIN.NM_HEADER FROM T_FO, DATA_PEMOHON, MIJIN, M_PAKET_DETAIL, T_FO_SUB_IJIN WHERE T_FO.NO_REGISTRASI = DATA_PEMOHON.NO_REGISTRASI AND TO_CHAR ( DATA_PEMOHON.TGL_REGISTRASI, 'ddmmyyyy' ) = TO_CHAR ( T_FO.TGL_REGISTRASI, 'ddmmyyyy' ) AND SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) = SUBSTR (MIJIN.KD_IJIN, 1, 4) AND SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) = SUBSTR ( T_FO_SUB_IJIN.KD_IJIN, 1, 4 ) AND T_FO.ID_PAKET = '$param1' AND T_FO.TGL_REGISTRASI BETWEEN TO_DATE ('$tgl1', 'yyyy-mm-dd') AND TO_DATE ('$tgl2', 'yyyy-mm-dd') AND MIJIN.NM_HEADER LIKE '%$param2%' AND DATA_PEMOHON.STS_TOLAK IS NULL AND DATA_PEMOHON.NO_SK IS NOT NULL ) ORDER BY NO_REGISTRASI ASC";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_tanggal_tolak_detail($tgl1 ='',$tgl2 ='',$param1='',$param2=''){
        	$sql = "SELECT * FROM ( SELECT DISTINCT T_FO.TGL_REGISTRASI, T_FO.NO_REGISTRASI, NAMA, ALAMAT, NAMA_PERUSAHAAN, ALAMAT_PT, SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) AS KD_HEADER, MIJIN.NM_HEADER FROM T_FO, DATA_PEMOHON, MIJIN, M_PAKET_DETAIL WHERE T_FO.NO_REGISTRASI = DATA_PEMOHON.NO_REGISTRASI AND TO_CHAR ( DATA_PEMOHON.TGL_REGISTRASI, 'ddmmyyyy' ) = TO_CHAR ( T_FO.TGL_REGISTRASI, 'ddmmyyyy' ) AND SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) = SUBSTR (MIJIN.KD_IJIN, 1, 4) AND T_FO.ID_PAKET = '$param1' AND T_FO.TGL_REGISTRASI BETWEEN TO_DATE ('$tgl1', 'yyyy-mm-dd') AND TO_DATE ('$tgl2', 'yyyy-mm-dd') AND ID_ALUR_PROSES != 100 and NM_HEADER like '%$param2%' AND DATA_PEMOHON.STS_TOLAK IS NOT NULL) ORDER BY NO_REGISTRASI ASC";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_waktu_proses($tgl1='',$tgl2='',$param1=''){
        	$sql = "SELECT HARI - ( SELECT COUNT (TANGGAL) FROM HARI_LIBUR WHERE TANGGAL BETWEEN TGL_PROSES AND SEKARANG ) AS TOTAL FROM ( SELECT TGL_PROSES, SYSDATE AS SEKARANG, TO_DATE ( TO_CHAR (SYSDATE, 'DD-MM-YYYY'), 'DD-MM-YYYY' ) - TO_DATE ( TO_CHAR (TGL_PROSES, 'DD-MM-YYYY'), 'DD-MM-YYYY' ) AS HARI FROM TEMPLATE_T_ALUR_PROSES WHERE NO_REGISTRASI = '$param1' AND TGL_PROSES = ( SELECT * FROM ( SELECT TGL_PROSES FROM TEMPLATE_T_ALUR_PROSES WHERE NO_REGISTRASI = '$param1' AND TGL_REGISTRASI BETWEEN TO_DATE ('$tgl1', 'yyyy-mm-dd') AND TO_DATE ('$tgl2', 'yyyy-mm-dd') AND ID_TUJUAN_ALUR_PROSES = '2' ORDER BY TGL_PROSES DESC ) WHERE ROWNUM = 1 ))";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_waktu_selesai($tgl1='',$tgl2='',$param1=''){
        	$sql = "SELECT TO_DATE ( TO_CHAR (tgl_terbit, 'DD-MM-YYYY'), 'DD-MM-YYYY' ) - TO_DATE ( TO_CHAR (TGL_PROSES, 'DD-MM-YYYY'), 'DD-MM-YYYY' ) - ( SELECT COUNT (TANGGAL) FROM HARI_LIBUR WHERE TANGGAL BETWEEN TGL_PROSES AND tgl_terbit ) AS TOTAL FROM ( SELECT TGL_PROSES, ( SELECT * FROM ( SELECT TGL_PROSES FROM TEMPLATE_T_ALUR_PROSES WHERE ID_TUJUAN_ALUR_PROSES = 5 AND NO_REGISTRASI = '$param1' ORDER BY TGL_PROSES DESC ) WHERE ROWNUM = 1 ) AS tgl_terbit FROM TEMPLATE_T_ALUR_PROSES WHERE TEMPLATE_T_ALUR_PROSES.NO_REGISTRASI = '$param1' AND TGL_PROSES = ( SELECT * FROM ( SELECT TGL_PROSES FROM TEMPLATE_T_ALUR_PROSES WHERE NO_REGISTRASI = '$param1' AND TGL_REGISTRASI BETWEEN TO_DATE ('$tgl1', 'yyyy-mm-dd') AND TO_DATE ('$tgl2', 'yyyy-mm-dd') AND ID_TUJUAN_ALUR_PROSES = '2' ORDER BY TGL_PROSES DESC ) WHERE ROWNUM = 1 )) WHERE ROWNUM = 1";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_waktu_selesai_imb($tgl1='',$tgl2='',$param1='',$param2=''){
        	$sql = "SELECT TO_DATE (SELESAI, 'DD-MM-YYYY') - TO_DATE (MULAI, 'DD-MM-YYYY') - ( SELECT COUNT (TANGGAL) FROM HARI_LIBUR WHERE TANGGAL BETWEEN MULAI AND SELESAI ) AS HARI FROM ( SELECT TGL_STATUS AS MULAI FROM VW_".$param2."_DETIL WHERE NO_REGISTRASI = '$param1' AND STATUS = 'PEMBAYARAN' AND TGL_REGISTRASI BETWEEN TO_DATE ('$tgl1', 'yyyy-mm-dd') AND TO_DATE ('$tgl2', 'yyyy-mm-dd')), ( SELECT TGL_STATUS AS SELESAI FROM VW_".$param2."_DETIL WHERE NO_REGISTRASI = '$param1' AND STATUS = 'PENGESAHAN SK' AND TGL_REGISTRASI BETWEEN TO_DATE ('$tgl1', 'yyyy-mm-dd') AND TO_DATE ('$tgl2', 'yyyy-mm-dd'))";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_waktu_proses_imb($tgl1='',$tgl2='',$param1=''){
        	$sql = "SELECT TO_DATE (SYSDATE, 'DD-MM-YYYY') - TO_DATE ( TGL_REGISTRASI, 'DD-MM-YYYY' ) - ( SELECT COUNT (TANGGAL) FROM HARI_LIBUR WHERE TANGGAL BETWEEN TGL_REGISTRASI AND SYSDATE ) AS TOTAL FROM T_FO WHERE NO_REGISTRASI = '$param1' AND TGL_REGISTRASI BETWEEN TO_DATE ('$tgl1', 'yyyy-mm-dd') AND TO_DATE ('$tgl2', 'yyyy-mm-dd')";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_histori_details($tgl1='',$param1='', $param2=''){
        	$sql = "SELECT DISTINCT * FROM ( SELECT T_FO.NO_REGISTRASI, T_FO.NAMA, TEMPLATE_M_PETUGAS_LOKAL.NAMA AS NAMA_PETUGAS, TEMPLATE_T_ALUR_PROSES.TGL_PROSES, TEMPLATE_M_ALUR_PROSES.NAMA_ALUR_PROSES, TEMPLATE_T_ALUR_PROSES.KETERANGAN, MIJIN.NM_HEADER FROM T_FO, TEMPLATE_T_ALUR_PROSES, TEMPLATE_M_ALUR_PROSES, TEMPLATE_M_PETUGAS_LOKAL, DATA_PEMOHON, T_FO_SUB_IJIN, MIJIN WHERE T_FO.NO_REGISTRASI = TEMPLATE_T_ALUR_PROSES.NO_REGISTRASI AND T_FO.NO_REGISTRASI = DATA_PEMOHON.NO_REGISTRASI AND TO_CHAR ( T_FO.TGL_REGISTRASI, 'ddmmyyyy' ) = TO_CHAR ( TEMPLATE_T_ALUR_PROSES.TGL_REGISTRASI, 'ddmmyyyy' ) AND SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) = SUBSTR (MIJIN.KD_IJIN, 1, 4) AND SUBSTR (DATA_PEMOHON.KD_IJIN, 1, 4) = SUBSTR (T_FO_SUB_IJIN.KD_IJIN, 1, 4) AND TEMPLATE_M_ALUR_PROSES.ID_ALUR_PROSES = TEMPLATE_T_ALUR_PROSES.ID_TUJUAN_ALUR_PROSES AND TEMPLATE_T_ALUR_PROSES.ID_USER = TEMPLATE_M_PETUGAS_LOKAL.ID_PETUGAS AND TEMPLATE_T_ALUR_PROSES.TGL_REGISTRASI = TO_DATE ('$tgl1', 'yyyy-mm-dd') AND TEMPLATE_T_ALUR_PROSES.NO_REGISTRASI = '$param1' AND MIJIN.NM_HEADER LIKE '%$param2%' ORDER BY TGL_PROSES DESC ) ORDER BY TGL_PROSES DESC";

			$query = $this->db->query($sql);
			return $query->result();
        }
        function get_histori_details_imb($tgl1='',$param1='',$param2=''){
        	$sql = "SELECT * FROM VW_".$param2."_DETIL WHERE NO_REGISTRASI = '$param1' AND TGL_REGISTRASI = TO_DATE ('$tgl1', 'yyyy-mm-dd')";

			$query = $this->db->query($sql);
			return $query->result();
        }
	}
?>
